id: P003297
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25670
  title: བོད་ཀྱི་གནའ་རབས་རྩོམ་རིག་སྙིང་བསྡུས་གསལ་བཀྲོལ།
  author: ''
  volumes:
    207af6ac149d4097a9184cd2865966f8:
      image_group_id: I1KG25672
      title: ''
      volume_number: 1
      total_pages: 227
      base_file: v001.txt
