id: IEFA5AD85
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:29:17+00:00'
last_modified: '2022-06-07T18:55:17.434457+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25670
  title: བོད་ཀྱི་གནའ་རབས་རྩོམ་རིག་སྙིང་བསྡུས་གསལ་བཀྲོལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    49C1:
      image_group_id: I1KG25672
      title: ''
      total_pages: 227
      order: 1
      base_file: 49C1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
